---
name: ci

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: for hand-shake come close
        run: echo "Come close"

      - name: raise hand towards each-other
        run: echo "Hand shaked"
    
