---
name: ci

on:
  push:  # workflow_dispatch:
    branches: [main]  # inputs:environment: description: this is the environment value where this workflow runs options: -dev, -stag, -prod
    paths:
      - "**.html"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: for hand-shake come close
        run: echo "Come close"

      - name: raise hand towards each-other
        run: echo "Hand shaked"
    
