---
name: Deploy to Server

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: SSH to Prod Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            echo "Starting Deployment"
            mkdir Devops