---
name: devsecops-pipeline
 
on:
  workflow_dispatch:

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yaml

  secrets-scan:
    uses: ./.github/workflows/secret-scan.yaml 

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yaml

  docker-scan:
    uses: ./.github/workflows/docker-lint.yaml    