---
name: devsecops-pipeline
 
on:
  push:
    branches: [main]

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yaml

  secrets-scan:
    uses: ./.github/workflows/secret-scan.yaml
    secrets: inherit

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yaml

  docker-scan:
    uses: ./.github/workflows/docker-lint.yaml    

  build:
    needs: [code-quality,secrets-scan,dependency-scan,docker-scan]
    uses: ./.github/workflows/docker-build-push.yaml 
    secrets: inherit

  trivy:
    needs: [build]  
    uses: ./.github/workflows/image-scan.yaml