---
name: Portfolio

on:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup github pages
        uses: actions/configure-pages@v4  

      - name: upload static files
        uses: actions/upload-pages-artifacts@v4  

      - name: Deploy to Github pages
        uses: actions/deploy-pages@v4   